/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import com.aspose.cloud.threed.model.FileSystem;
import com.aspose.cloud.threed.model.SaveFormat;
import com.aspose.cloud.threed.model.SaveOptions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.List;

/**
 * AMFSaveOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-14T15:01:31.292+08:00")
public class AMFSaveOption extends SaveOptions {
  @SerializedName("EnableCompression")
  private Boolean enableCompression = null;

  public AMFSaveOption enableCompression(Boolean enableCompression) {
    this.enableCompression = enableCompression;
    return this;
  }

   /**
   * Whether to use compression to reduce the final file size, default value is true.
   * @return enableCompression
  **/
  @ApiModelProperty(value = "Whether to use compression to reduce the final file size, default value is true.")
  public Boolean isEnableCompression() {
    return enableCompression;
  }

  public void setEnableCompression(Boolean enableCompression) {
    this.enableCompression = enableCompression;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AMFSaveOption amFSaveOption = (AMFSaveOption) o;
    return Objects.equals(this.enableCompression, amFSaveOption.enableCompression) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enableCompression, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AMFSaveOption {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    enableCompression: ").append(toIndentedString(enableCompression)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

