/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The Box Entity
 */
@ApiModel(description = "The Box Entity")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-09T10:19:53.827+08:00")
public class Box {
  @SerializedName("Length")
  private Double length = null;

  @SerializedName("Width")
  private Double width = null;

  @SerializedName("Height")
  private Double height = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("LengthSegments")
  private Integer lengthSegments = null;

  @SerializedName("WidthSegments")
  private Integer widthSegments = null;

  @SerializedName("HeightSegments")
  private Integer heightSegments = null;

  public Box length(Double length) {
    this.length = length;
    return this;
  }

   /**
   * Gets or sets the length of the box             
   * @return length
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the length of the box             ")
  public Double getLength() {
    return length;
  }

  public void setLength(Double length) {
    this.length = length;
  }

  public Box width(Double width) {
    this.width = width;
    return this;
  }

   /**
   * Gets or sets the width of the box
   * @return width
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the width of the box")
  public Double getWidth() {
    return width;
  }

  public void setWidth(Double width) {
    this.width = width;
  }

  public Box height(Double height) {
    this.height = height;
    return this;
  }

   /**
   * Gets or sets the height of the box
   * @return height
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the height of the box")
  public Double getHeight() {
    return height;
  }

  public void setHeight(Double height) {
    this.height = height;
  }

  public Box name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Gets or sets the name of the box             
   * @return name
  **/
  @ApiModelProperty(value = "Gets or sets the name of the box             ")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Box lengthSegments(Integer lengthSegments) {
    this.lengthSegments = lengthSegments;
    return this;
  }

   /**
   * Gets or sets the lengthSegments of the box
   * @return lengthSegments
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the lengthSegments of the box")
  public Integer getLengthSegments() {
    return lengthSegments;
  }

  public void setLengthSegments(Integer lengthSegments) {
    this.lengthSegments = lengthSegments;
  }

  public Box widthSegments(Integer widthSegments) {
    this.widthSegments = widthSegments;
    return this;
  }

   /**
   * Gets or sets the widthSegments of the box
   * @return widthSegments
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the widthSegments of the box")
  public Integer getWidthSegments() {
    return widthSegments;
  }

  public void setWidthSegments(Integer widthSegments) {
    this.widthSegments = widthSegments;
  }

  public Box heightSegments(Integer heightSegments) {
    this.heightSegments = heightSegments;
    return this;
  }

   /**
   * Gets or sets the heightSegments of the box
   * @return heightSegments
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the heightSegments of the box")
  public Integer getHeightSegments() {
    return heightSegments;
  }

  public void setHeightSegments(Integer heightSegments) {
    this.heightSegments = heightSegments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Box box = (Box) o;
    return Objects.equals(this.length, box.length) &&
        Objects.equals(this.width, box.width) &&
        Objects.equals(this.height, box.height) &&
        Objects.equals(this.name, box.name) &&
        Objects.equals(this.lengthSegments, box.lengthSegments) &&
        Objects.equals(this.widthSegments, box.widthSegments) &&
        Objects.equals(this.heightSegments, box.heightSegments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(length, width, height, name, lengthSegments, widthSegments, heightSegments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Box {\n");
    
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    lengthSegments: ").append(toIndentedString(lengthSegments)).append("\n");
    sb.append("    widthSegments: ").append(toIndentedString(widthSegments)).append("\n");
    sb.append("    heightSegments: ").append(toIndentedString(heightSegments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

