/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import com.aspose.cloud.threed.model.ColladaTransformStyle;
import com.aspose.cloud.threed.model.FileSystem;
import com.aspose.cloud.threed.model.SaveFormat;
import com.aspose.cloud.threed.model.SaveOptions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.List;

/**
 * ColladaSaveOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-14T15:01:31.292+08:00")
public class ColladaSaveOption extends SaveOptions {
  @SerializedName("Indented")
  private Boolean indented = null;

  @SerializedName("TransformStyle")
  private ColladaTransformStyle transformStyle = null;

  public ColladaSaveOption indented(Boolean indented) {
    this.indented = indented;
    return this;
  }

   /**
   * Gets or sets whether the exported XML document is indented.
   * @return indented
  **/
  @ApiModelProperty(value = "Gets or sets whether the exported XML document is indented.")
  public Boolean isIndented() {
    return indented;
  }

  public void setIndented(Boolean indented) {
    this.indented = indented;
  }

  public ColladaSaveOption transformStyle(ColladaTransformStyle transformStyle) {
    this.transformStyle = transformStyle;
    return this;
  }

   /**
   * Gets or sets  of the Transform Style.
   * @return transformStyle
  **/
  @ApiModelProperty(value = "Gets or sets  of the Transform Style.")
  public ColladaTransformStyle getTransformStyle() {
    return transformStyle;
  }

  public void setTransformStyle(ColladaTransformStyle transformStyle) {
    this.transformStyle = transformStyle;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ColladaSaveOption colladaSaveOption = (ColladaSaveOption) o;
    return Objects.equals(this.indented, colladaSaveOption.indented) &&
        Objects.equals(this.transformStyle, colladaSaveOption.transformStyle) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(indented, transformStyle, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ColladaSaveOption {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    indented: ").append(toIndentedString(indented)).append("\n");
    sb.append("    transformStyle: ").append(toIndentedString(transformStyle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

