/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The node&#39;s transform style of node.
 */
@JsonAdapter(ColladaTransformStyle.Adapter.class)
public enum ColladaTransformStyle {
  
  Components(0),
  
  Matrix(1);

  private Integer value;

  ColladaTransformStyle(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ColladaTransformStyle fromValue(String text) {
    for (ColladaTransformStyle b : ColladaTransformStyle.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ColladaTransformStyle> {
    @Override
    public void write(final JsonWriter jsonWriter, final ColladaTransformStyle enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ColladaTransformStyle read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return ColladaTransformStyle.fromValue(String.valueOf(value));
    }
  }
}

