/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import com.aspose.cloud.threed.model.Box;
import com.aspose.cloud.threed.model.Cylinder;
import com.aspose.cloud.threed.model.Plane;
import com.aspose.cloud.threed.model.Sphere;
import com.aspose.cloud.threed.model.Torus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Entity class             
 */
@ApiModel(description = "Entity class             ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-09T10:19:53.827+08:00")
public class Entity {
  @SerializedName("Type")
  private String type = null;

  @SerializedName("Box")
  private Box box = null;

  @SerializedName("Cylinder")
  private Cylinder cylinder = null;

  @SerializedName("Sphere")
  private Sphere sphere = null;

  @SerializedName("Torus")
  private Torus torus = null;

  @SerializedName("Plane")
  private Plane plane = null;

  public Entity type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Box/Cylinder/Sphere/Torus/Plane
   * @return type
  **/
  @ApiModelProperty(value = "Box/Cylinder/Sphere/Torus/Plane")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Entity box(Box box) {
    this.box = box;
    return this;
  }

   /**
   * Gets or sets Box entity
   * @return box
  **/
  @ApiModelProperty(value = "Gets or sets Box entity")
  public Box getBox() {
    return box;
  }

  public void setBox(Box box) {
    this.box = box;
  }

  public Entity cylinder(Cylinder cylinder) {
    this.cylinder = cylinder;
    return this;
  }

   /**
   * Gets or sets Cylinder entity
   * @return cylinder
  **/
  @ApiModelProperty(value = "Gets or sets Cylinder entity")
  public Cylinder getCylinder() {
    return cylinder;
  }

  public void setCylinder(Cylinder cylinder) {
    this.cylinder = cylinder;
  }

  public Entity sphere(Sphere sphere) {
    this.sphere = sphere;
    return this;
  }

   /**
   * Gets or sets Sphere entity
   * @return sphere
  **/
  @ApiModelProperty(value = "Gets or sets Sphere entity")
  public Sphere getSphere() {
    return sphere;
  }

  public void setSphere(Sphere sphere) {
    this.sphere = sphere;
  }

  public Entity torus(Torus torus) {
    this.torus = torus;
    return this;
  }

   /**
   * Gets or sets Torus entity
   * @return torus
  **/
  @ApiModelProperty(value = "Gets or sets Torus entity")
  public Torus getTorus() {
    return torus;
  }

  public void setTorus(Torus torus) {
    this.torus = torus;
  }

  public Entity plane(Plane plane) {
    this.plane = plane;
    return this;
  }

   /**
   * Gets or sets Plane entity
   * @return plane
  **/
  @ApiModelProperty(value = "Gets or sets Plane entity")
  public Plane getPlane() {
    return plane;
  }

  public void setPlane(Plane plane) {
    this.plane = plane;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Entity entity = (Entity) o;
    return Objects.equals(this.type, entity.type) &&
        Objects.equals(this.box, entity.box) &&
        Objects.equals(this.cylinder, entity.cylinder) &&
        Objects.equals(this.sphere, entity.sphere) &&
        Objects.equals(this.torus, entity.torus) &&
        Objects.equals(this.plane, entity.plane);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, box, cylinder, sphere, torus, plane);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Entity {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    box: ").append(toIndentedString(box)).append("\n");
    sb.append("    cylinder: ").append(toIndentedString(cylinder)).append("\n");
    sb.append("    sphere: ").append(toIndentedString(sphere)).append("\n");
    sb.append("    torus: ").append(toIndentedString(torus)).append("\n");
    sb.append("    plane: ").append(toIndentedString(plane)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

