/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import com.aspose.cloud.threed.model.SaveFormat;
import com.aspose.cloud.threed.model.SaveOptions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.List;

/**
 * ObjSaveOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-09T10:19:53.827+08:00")
public class ObjSaveOption extends SaveOptions {
  @SerializedName("Verbose")
  private Boolean verbose = null;

  @SerializedName("SerializeW")
  private Boolean serializeW = null;

  @SerializedName("EnableMaterials")
  private Boolean enableMaterials = null;

  @SerializedName("FlipCoordinateSystem")
  private Boolean flipCoordinateSystem = null;

  public ObjSaveOption verbose(Boolean verbose) {
    this.verbose = verbose;
    return this;
  }

   /**
   * Gets or sets whether generate comments for each section.
   * @return verbose
  **/
  @ApiModelProperty(value = "Gets or sets whether generate comments for each section.")
  public Boolean Verbose() {
    return verbose;
  }

  public void setVerbose(Boolean verbose) {
    this.verbose = verbose;
  }

  public ObjSaveOption serializeW(Boolean serializeW) {
    this.serializeW = serializeW;
    return this;
  }

   /**
   * Gets or sets whether serialize W component in model&#39;s vertex position.
   * @return serializeW
  **/
  @ApiModelProperty(value = "Gets or sets whether serialize W component in model's vertex position.")
  public Boolean SerializeW() {
    return serializeW;
  }

  public void setSerializeW(Boolean serializeW) {
    this.serializeW = serializeW;
  }

  public ObjSaveOption enableMaterials(Boolean enableMaterials) {
    this.enableMaterials = enableMaterials;
    return this;
  }

   /**
   * Gets or sets whether import/export materials for each object.
   * @return enableMaterials
  **/
  @ApiModelProperty(value = "Gets or sets whether import/export materials for each object.")
  public Boolean EnableMaterials() {
    return enableMaterials;
  }

  public void setEnableMaterials(Boolean enableMaterials) {
    this.enableMaterials = enableMaterials;
  }

  public ObjSaveOption flipCoordinateSystem(Boolean flipCoordinateSystem) {
    this.flipCoordinateSystem = flipCoordinateSystem;
    return this;
  }

   /**
   * Gets or sets whether flip coordinate system of control points/normal during importing/exporting.
   * @return flipCoordinateSystem
  **/
  @ApiModelProperty(value = "Gets or sets whether flip coordinate system of control points/normal during importing/exporting.")
  public Boolean FlipCoordinateSystem() {
    return flipCoordinateSystem;
  }

  public void setFlipCoordinateSystem(Boolean flipCoordinateSystem) {
    this.flipCoordinateSystem = flipCoordinateSystem;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjSaveOption objSaveOption = (ObjSaveOption) o;
    return Objects.equals(this.verbose, objSaveOption.verbose) &&
        Objects.equals(this.serializeW, objSaveOption.serializeW) &&
        Objects.equals(this.enableMaterials, objSaveOption.enableMaterials) &&
        Objects.equals(this.flipCoordinateSystem, objSaveOption.flipCoordinateSystem) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(verbose, serializeW, enableMaterials, flipCoordinateSystem, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjSaveOption {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    verbose: ").append(toIndentedString(verbose)).append("\n");
    sb.append("    serializeW: ").append(toIndentedString(serializeW)).append("\n");
    sb.append("    enableMaterials: ").append(toIndentedString(enableMaterials)).append("\n");
    sb.append("    flipCoordinateSystem: ").append(toIndentedString(flipCoordinateSystem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

