/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Render mode specifies the style in which the 3D artwork is rendered.
 */
@JsonAdapter(PdfLightingScheme.Adapter.class)
public enum PdfLightingScheme {
  
  Artwork(0),
  
  None(1),
  
  White(2),
  
  Day(3),
  
  Night(4),
  
  Hard(5),
  
  Primary(6),
  
  Blue(7),
  
  Red(8),
  
  Cube(9),
  
  CAD(10),
  
  Headlamp(11);

  private Integer value;

  PdfLightingScheme(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PdfLightingScheme fromValue(String text) {
    for (PdfLightingScheme b : PdfLightingScheme.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PdfLightingScheme> {
    @Override
    public void write(final JsonWriter jsonWriter, final PdfLightingScheme enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PdfLightingScheme read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return PdfLightingScheme.fromValue(String.valueOf(value));
    }
  }
}

