/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Render mode specifies the style in which the 3D artwork is rendered.
 */
@JsonAdapter(PdfRenderMode.Adapter.class)
public enum PdfRenderMode {
  
  Solid(0),
  
  SolidWireframe(1),
  
  Transparent(2),
  
  TransparentWireframe(3),
  
  BoundingBox(4),
  
  TransparentBoundingBox(5),
  
  TransparentBoundingBoxOutline(6),
  
  Wireframe(7),
  
  ShadedWireframe(8),
  
  HiddenWireframe(9),
  
  Vertices(10),
  
  ShadedVertices(11),
  
  Illustration(12),
  
  SolidOutline(13),
  
  ShadedIllustration(14);

  private Integer value;

  PdfRenderMode(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PdfRenderMode fromValue(String text) {
    for (PdfRenderMode b : PdfRenderMode.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PdfRenderMode> {
    @Override
    public void write(final JsonWriter jsonWriter, final PdfRenderMode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PdfRenderMode read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return PdfRenderMode.fromValue(String.valueOf(value));
    }
  }
}

