/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import com.aspose.cloud.threed.model.PdfLightingScheme;
import com.aspose.cloud.threed.model.PdfRenderMode;
import com.aspose.cloud.threed.model.SaveFormat;
import com.aspose.cloud.threed.model.SaveOptions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.List;

/**
 * PdfSaveOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-09T10:19:53.827+08:00")
public class PdfSaveOption extends SaveOptions {
  @SerializedName("FlipCoordinateSystem")
  private Boolean flipCoordinateSystem = null;

  @SerializedName("RenderMode")
  private PdfRenderMode renderMode = null;

  @SerializedName("LightingScheme")
  private PdfLightingScheme lightingScheme = null;

  public PdfSaveOption flipCoordinateSystem(Boolean flipCoordinateSystem) {
    this.flipCoordinateSystem = flipCoordinateSystem;
    return this;
  }

   /**
   * Gets or sets to flip the coordinate system of the scene during exporting.
   * @return flipCoordinateSystem
  **/
  @ApiModelProperty(value = "Gets or sets to flip the coordinate system of the scene during exporting.")
  public Boolean FlipCoordinateSystem() {
    return flipCoordinateSystem;
  }

  public void setFlipCoordinateSystem(Boolean flipCoordinateSystem) {
    this.flipCoordinateSystem = flipCoordinateSystem;
  }

  public PdfSaveOption renderMode(PdfRenderMode renderMode) {
    this.renderMode = renderMode;
    return this;
  }

   /**
   * Render mode specifies the style in which the 3D artwork is rendered.
   * @return renderMode
  **/
  @ApiModelProperty(value = "Render mode specifies the style in which the 3D artwork is rendered.")
  public PdfRenderMode getRenderMode() {
    return renderMode;
  }

  public void setRenderMode(PdfRenderMode renderMode) {
    this.renderMode = renderMode;
  }

  public PdfSaveOption lightingScheme(PdfLightingScheme lightingScheme) {
    this.lightingScheme = lightingScheme;
    return this;
  }

   /**
   * LightingScheme specifies the lighting to apply to 3D artwork.
   * @return lightingScheme
  **/
  @ApiModelProperty(value = "LightingScheme specifies the lighting to apply to 3D artwork.")
  public PdfLightingScheme getLightingScheme() {
    return lightingScheme;
  }

  public void setLightingScheme(PdfLightingScheme lightingScheme) {
    this.lightingScheme = lightingScheme;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PdfSaveOption pdfSaveOption = (PdfSaveOption) o;
    return Objects.equals(this.flipCoordinateSystem, pdfSaveOption.flipCoordinateSystem) &&
        Objects.equals(this.renderMode, pdfSaveOption.renderMode) &&
        Objects.equals(this.lightingScheme, pdfSaveOption.lightingScheme) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flipCoordinateSystem, renderMode, lightingScheme, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PdfSaveOption {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    flipCoordinateSystem: ").append(toIndentedString(flipCoordinateSystem)).append("\n");
    sb.append("    renderMode: ").append(toIndentedString(renderMode)).append("\n");
    sb.append("    lightingScheme: ").append(toIndentedString(lightingScheme)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

