/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import com.aspose.cloud.threed.model.FileContentType;
import com.aspose.cloud.threed.model.FileSystem;
import com.aspose.cloud.threed.model.SaveFormat;
import com.aspose.cloud.threed.model.SaveOptions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PlySaveOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-14T15:01:31.292+08:00")
public class PlySaveOption extends SaveOptions {
  @SerializedName("FlipCoordinate")
  private Boolean flipCoordinate = null;

  @SerializedName("VertexElement")
  private String vertexElement = null;

  @SerializedName("PositionComponents")
  private List<String> positionComponents = null;

  @SerializedName("FaceElement")
  private String faceElement = null;

  @SerializedName("FaceProperty")
  private String faceProperty = null;

  @SerializedName("FileContentType")
  private FileContentType fileContentType = null;

  public PlySaveOption flipCoordinate(Boolean flipCoordinate) {
    this.flipCoordinate = flipCoordinate;
    return this;
  }

   /**
   * Flip the coordinate while saving the scene, default value is true.
   * @return flipCoordinate
  **/
  @ApiModelProperty(value = "Flip the coordinate while saving the scene, default value is true.")
  public Boolean isFlipCoordinate() {
    return flipCoordinate;
  }

  public void setFlipCoordinate(Boolean flipCoordinate) {
    this.flipCoordinate = flipCoordinate;
  }

  public PlySaveOption vertexElement(String vertexElement) {
    this.vertexElement = vertexElement;
    return this;
  }

   /**
   * The element name for the vertex data, default value is \&quot;vertex\&quot;.
   * @return vertexElement
  **/
  @ApiModelProperty(value = "The element name for the vertex data, default value is \"vertex\".")
  public String getVertexElement() {
    return vertexElement;
  }

  public void setVertexElement(String vertexElement) {
    this.vertexElement = vertexElement;
  }

  public PlySaveOption positionComponents(List<String> positionComponents) {
    this.positionComponents = positionComponents;
    return this;
  }

  public PlySaveOption addPositionComponentsItem(String positionComponentsItem) {
    if (this.positionComponents == null) {
      this.positionComponents = new ArrayList<String>();
    }
    this.positionComponents.add(positionComponentsItem);
    return this;
  }

   /**
   * The component names for position data, default value is (\&quot;x\&quot;, \&quot;y\&quot;, \&quot;z\&quot;)
   * @return positionComponents
  **/
  @ApiModelProperty(value = "The component names for position data, default value is (\"x\", \"y\", \"z\")")
  public List<String> getPositionComponents() {
    return positionComponents;
  }

  public void setPositionComponents(List<String> positionComponents) {
    this.positionComponents = positionComponents;
  }

  public PlySaveOption faceElement(String faceElement) {
    this.faceElement = faceElement;
    return this;
  }

   /**
   * The element name for the face data, default value is face.
   * @return faceElement
  **/
  @ApiModelProperty(value = "The element name for the face data, default value is face.")
  public String getFaceElement() {
    return faceElement;
  }

  public void setFaceElement(String faceElement) {
    this.faceElement = faceElement;
  }

  public PlySaveOption faceProperty(String faceProperty) {
    this.faceProperty = faceProperty;
    return this;
  }

   /**
   * The property name for the face data, default value is vertex_index.
   * @return faceProperty
  **/
  @ApiModelProperty(value = "The property name for the face data, default value is vertex_index.")
  public String getFaceProperty() {
    return faceProperty;
  }

  public void setFaceProperty(String faceProperty) {
    this.faceProperty = faceProperty;
  }

  public PlySaveOption fileContentType(FileContentType fileContentType) {
    this.fileContentType = fileContentType;
    return this;
  }

   /**
   * Gets or sets  of the FileContent Style.
   * @return fileContentType
  **/
  @ApiModelProperty(value = "Gets or sets  of the FileContent Style.")
  public FileContentType getFileContentType() {
    return fileContentType;
  }

  public void setFileContentType(FileContentType fileContentType) {
    this.fileContentType = fileContentType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlySaveOption plySaveOption = (PlySaveOption) o;
    return Objects.equals(this.flipCoordinate, plySaveOption.flipCoordinate) &&
        Objects.equals(this.vertexElement, plySaveOption.vertexElement) &&
        Objects.equals(this.positionComponents, plySaveOption.positionComponents) &&
        Objects.equals(this.faceElement, plySaveOption.faceElement) &&
        Objects.equals(this.faceProperty, plySaveOption.faceProperty) &&
        Objects.equals(this.fileContentType, plySaveOption.fileContentType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flipCoordinate, vertexElement, positionComponents, faceElement, faceProperty, fileContentType, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlySaveOption {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    flipCoordinate: ").append(toIndentedString(flipCoordinate)).append("\n");
    sb.append("    vertexElement: ").append(toIndentedString(vertexElement)).append("\n");
    sb.append("    positionComponents: ").append(toIndentedString(positionComponents)).append("\n");
    sb.append("    faceElement: ").append(toIndentedString(faceElement)).append("\n");
    sb.append("    faceProperty: ").append(toIndentedString(faceProperty)).append("\n");
    sb.append("    fileContentType: ").append(toIndentedString(fileContentType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

