/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * SaveFormat type
 */
@JsonAdapter(SaveFormat.Adapter.class)
public enum SaveFormat {
  
  //AMF
  NUMBER_0(0),
  //Collada
  NUMBER_1(1),
  //Discreet3DS
  NUMBER_2(2),
  //Draco
  NUMBER_3(3),
  //FBX
  NUMBER_4(4),
  //GLTF
  NUMBER_5(5),
  //Obj
  NUMBER_6(6),
  //PDF
  NUMBER_7(7),
  //PLY
  NUMBER_8(8),
  //Rvm
  NUMBER_9(9),
  //STL
  NUMBER_10(10),
  //U3D
  NUMBER_11(11);

  private Integer value;

  SaveFormat(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SaveFormat fromValue(String text) {
    for (SaveFormat b : SaveFormat.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<SaveFormat> {
    @Override
    public void write(final JsonWriter jsonWriter, final SaveFormat enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SaveFormat read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return SaveFormat.fromValue(String.valueOf(value));
    }
  }
}

