/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The Sphere Entity
 */
@ApiModel(description = "The Sphere Entity")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-14T15:01:31.292+08:00")
public class Sphere {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("WidthSegments")
  private Integer widthSegments = null;

  @SerializedName("HeightSegments")
  private Integer heightSegments = null;

  @SerializedName("PhiStart")
  private Double phiStart = null;

  @SerializedName("PhiLength")
  private Double phiLength = null;

  @SerializedName("ThetaStart")
  private Double thetaStart = null;

  @SerializedName("ThetaLength")
  private Double thetaLength = null;

  @SerializedName("Radius")
  private Double radius = null;

  public Sphere name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Gets or sets the Name of Sphere.
   * @return name
  **/
  @ApiModelProperty(value = "Gets or sets the Name of Sphere.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Sphere widthSegments(Integer widthSegments) {
    this.widthSegments = widthSegments;
    return this;
  }

   /**
   * Gets or sets the width segments.
   * @return widthSegments
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the width segments.")
  public Integer getWidthSegments() {
    return widthSegments;
  }

  public void setWidthSegments(Integer widthSegments) {
    this.widthSegments = widthSegments;
  }

  public Sphere heightSegments(Integer heightSegments) {
    this.heightSegments = heightSegments;
    return this;
  }

   /**
   * Gets or sets the height segments.             
   * @return heightSegments
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the height segments.             ")
  public Integer getHeightSegments() {
    return heightSegments;
  }

  public void setHeightSegments(Integer heightSegments) {
    this.heightSegments = heightSegments;
  }

  public Sphere phiStart(Double phiStart) {
    this.phiStart = phiStart;
    return this;
  }

   /**
   * Gets or sets the phi start.             
   * @return phiStart
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the phi start.             ")
  public Double getPhiStart() {
    return phiStart;
  }

  public void setPhiStart(Double phiStart) {
    this.phiStart = phiStart;
  }

  public Sphere phiLength(Double phiLength) {
    this.phiLength = phiLength;
    return this;
  }

   /**
   * Gets or sets the length of the phi.
   * @return phiLength
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the length of the phi.")
  public Double getPhiLength() {
    return phiLength;
  }

  public void setPhiLength(Double phiLength) {
    this.phiLength = phiLength;
  }

  public Sphere thetaStart(Double thetaStart) {
    this.thetaStart = thetaStart;
    return this;
  }

   /**
   * Gets or sets the theta start.             
   * @return thetaStart
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the theta start.             ")
  public Double getThetaStart() {
    return thetaStart;
  }

  public void setThetaStart(Double thetaStart) {
    this.thetaStart = thetaStart;
  }

  public Sphere thetaLength(Double thetaLength) {
    this.thetaLength = thetaLength;
    return this;
  }

   /**
   * Gets or sets the length of the theta.
   * @return thetaLength
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the length of the theta.")
  public Double getThetaLength() {
    return thetaLength;
  }

  public void setThetaLength(Double thetaLength) {
    this.thetaLength = thetaLength;
  }

  public Sphere radius(Double radius) {
    this.radius = radius;
    return this;
  }

   /**
   * Gets or sets the radius 
   * @return radius
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the radius ")
  public Double getRadius() {
    return radius;
  }

  public void setRadius(Double radius) {
    this.radius = radius;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sphere sphere = (Sphere) o;
    return Objects.equals(this.name, sphere.name) &&
        Objects.equals(this.widthSegments, sphere.widthSegments) &&
        Objects.equals(this.heightSegments, sphere.heightSegments) &&
        Objects.equals(this.phiStart, sphere.phiStart) &&
        Objects.equals(this.phiLength, sphere.phiLength) &&
        Objects.equals(this.thetaStart, sphere.thetaStart) &&
        Objects.equals(this.thetaLength, sphere.thetaLength) &&
        Objects.equals(this.radius, sphere.radius);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, widthSegments, heightSegments, phiStart, phiLength, thetaStart, thetaLength, radius);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sphere {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    widthSegments: ").append(toIndentedString(widthSegments)).append("\n");
    sb.append("    heightSegments: ").append(toIndentedString(heightSegments)).append("\n");
    sb.append("    phiStart: ").append(toIndentedString(phiStart)).append("\n");
    sb.append("    phiLength: ").append(toIndentedString(phiLength)).append("\n");
    sb.append("    thetaStart: ").append(toIndentedString(thetaStart)).append("\n");
    sb.append("    thetaLength: ").append(toIndentedString(thetaLength)).append("\n");
    sb.append("    radius: ").append(toIndentedString(radius)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

