/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import com.aspose.cloud.threed.model.FileContentType;
import com.aspose.cloud.threed.model.SaveFormat;
import com.aspose.cloud.threed.model.SaveOptions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.List;

/**
 * STLSaveOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-09T10:19:53.827+08:00")
public class STLSaveOption extends SaveOptions {
  @SerializedName("FlipCoordinateSystem")
  private Boolean flipCoordinateSystem = null;

  @SerializedName("FileContentType")
  private FileContentType fileContentType = null;

  public STLSaveOption flipCoordinateSystem(Boolean flipCoordinateSystem) {
    this.flipCoordinateSystem = flipCoordinateSystem;
    return this;
  }

   /**
   * Gets or sets whether flip coordinate system of control points/normal during exporting.
   * @return flipCoordinateSystem
  **/
  @ApiModelProperty(value = "Gets or sets whether flip coordinate system of control points/normal during exporting.")
  public Boolean FlipCoordinateSystem() {
    return flipCoordinateSystem;
  }

  public void setFlipCoordinateSystem(Boolean flipCoordinateSystem) {
    this.flipCoordinateSystem = flipCoordinateSystem;
  }

  public STLSaveOption fileContentType(FileContentType fileContentType) {
    this.fileContentType = fileContentType;
    return this;
  }

   /**
   * Gets or sets  of the FileContent Style.
   * @return fileContentType
  **/
  @ApiModelProperty(value = "Gets or sets  of the FileContent Style.")
  public FileContentType getFileContentType() {
    return fileContentType;
  }

  public void setFileContentType(FileContentType fileContentType) {
    this.fileContentType = fileContentType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    STLSaveOption stLSaveOption = (STLSaveOption) o;
    return Objects.equals(this.flipCoordinateSystem, stLSaveOption.flipCoordinateSystem) &&
        Objects.equals(this.fileContentType, stLSaveOption.fileContentType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flipCoordinateSystem, fileContentType, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class STLSaveOption {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    flipCoordinateSystem: ").append(toIndentedString(flipCoordinateSystem)).append("\n");
    sb.append("    fileContentType: ").append(toIndentedString(fileContentType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

