/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The Torus Entity class
 */
@ApiModel(description = "The Torus Entity class")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-09T10:19:53.827+08:00")
public class Torus {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("Radius")
  private Double radius = null;

  @SerializedName("Tube")
  private Double tube = null;

  @SerializedName("RadialSegments")
  private Integer radialSegments = null;

  @SerializedName("TubularSegments")
  private Integer tubularSegments = null;

  @SerializedName("Arc")
  private Double arc = null;

  public Torus name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Gets or sets the Name of the torus.
   * @return name
  **/
  @ApiModelProperty(value = "Gets or sets the Name of the torus.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Torus radius(Double radius) {
    this.radius = radius;
    return this;
  }

   /**
   * Gets or sets the radius of the torus.             
   * @return radius
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the radius of the torus.             ")
  public Double getRadius() {
    return radius;
  }

  public void setRadius(Double radius) {
    this.radius = radius;
  }

  public Torus tube(Double tube) {
    this.tube = tube;
    return this;
  }

   /**
   * Gets or sets the radius of the tube.
   * @return tube
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the radius of the tube.")
  public Double getTube() {
    return tube;
  }

  public void setTube(Double tube) {
    this.tube = tube;
  }

  public Torus radialSegments(Integer radialSegments) {
    this.radialSegments = radialSegments;
    return this;
  }

   /**
   * Gets or sets the radial segments.
   * @return radialSegments
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the radial segments.")
  public Integer getRadialSegments() {
    return radialSegments;
  }

  public void setRadialSegments(Integer radialSegments) {
    this.radialSegments = radialSegments;
  }

  public Torus tubularSegments(Integer tubularSegments) {
    this.tubularSegments = tubularSegments;
    return this;
  }

   /**
   * Gets or sets the tubular segments.
   * @return tubularSegments
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the tubular segments.")
  public Integer getTubularSegments() {
    return tubularSegments;
  }

  public void setTubularSegments(Integer tubularSegments) {
    this.tubularSegments = tubularSegments;
  }

  public Torus arc(Double arc) {
    this.arc = arc;
    return this;
  }

   /**
   * Gets or sets the arc.
   * @return arc
  **/
  @ApiModelProperty(required = true, value = "Gets or sets the arc.")
  public Double getArc() {
    return arc;
  }

  public void setArc(Double arc) {
    this.arc = arc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Torus torus = (Torus) o;
    return Objects.equals(this.name, torus.name) &&
        Objects.equals(this.radius, torus.radius) &&
        Objects.equals(this.tube, torus.tube) &&
        Objects.equals(this.radialSegments, torus.radialSegments) &&
        Objects.equals(this.tubularSegments, torus.tubularSegments) &&
        Objects.equals(this.arc, torus.arc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, radius, tube, radialSegments, tubularSegments, arc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Torus {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    radius: ").append(toIndentedString(radius)).append("\n");
    sb.append("    tube: ").append(toIndentedString(tube)).append("\n");
    sb.append("    radialSegments: ").append(toIndentedString(radialSegments)).append("\n");
    sb.append("    tubularSegments: ").append(toIndentedString(tubularSegments)).append("\n");
    sb.append("    arc: ").append(toIndentedString(arc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

