/*
 * Aspose.ThreeD Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.aspose.cloud.threed.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A vector with three components.             
 */
@ApiModel(description = "A vector with three components.             ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-08-14T15:01:31.292+08:00")
public class Vector3 {
  @SerializedName("x")
  private Double x = null;

  @SerializedName("y")
  private Double y = null;

  @SerializedName("z")
  private Double z = null;

  @SerializedName("Length2")
  private Double length2 = null;

  @SerializedName("Length")
  private Double length = null;

  public Vector3 x(Double x) {
    this.x = x;
    return this;
  }

   /**
   * The x component.
   * @return x
  **/
  @ApiModelProperty(required = true, value = "The x component.")
  public Double getX() {
    return x;
  }

  public void setX(Double x) {
    this.x = x;
  }

  public Vector3 y(Double y) {
    this.y = y;
    return this;
  }

   /**
   * The y component.
   * @return y
  **/
  @ApiModelProperty(required = true, value = "The y component.")
  public Double getY() {
    return y;
  }

  public void setY(Double y) {
    this.y = y;
  }

  public Vector3 z(Double z) {
    this.z = z;
    return this;
  }

   /**
   * The z component.
   * @return z
  **/
  @ApiModelProperty(required = true, value = "The z component.")
  public Double getZ() {
    return z;
  }

  public void setZ(Double z) {
    this.z = z;
  }

  public Vector3 length2(Double length2) {
    this.length2 = length2;
    return this;
  }

   /**
   * Gets the square of the length.             
   * @return length2
  **/
  @ApiModelProperty(required = true, value = "Gets the square of the length.             ")
  public Double getLength2() {
    return length2;
  }

  public void setLength2(Double length2) {
    this.length2 = length2;
  }

  public Vector3 length(Double length) {
    this.length = length;
    return this;
  }

   /**
   * Gets the length of this vector.
   * @return length
  **/
  @ApiModelProperty(required = true, value = "Gets the length of this vector.")
  public Double getLength() {
    return length;
  }

  public void setLength(Double length) {
    this.length = length;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vector3 vector3 = (Vector3) o;
    return Objects.equals(this.x, vector3.x) &&
        Objects.equals(this.y, vector3.y) &&
        Objects.equals(this.z, vector3.z) &&
        Objects.equals(this.length2, vector3.length2) &&
        Objects.equals(this.length, vector3.length);
  }

  @Override
  public int hashCode() {
    return Objects.hash(x, y, z, length2, length);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vector3 {\n");
    
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    z: ").append(toIndentedString(z)).append("\n");
    sb.append("    length2: ").append(toIndentedString(length2)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

